# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "workflow" branch
  push:
    branches: ["workflow"]
  pull_request:
    branches: ["workflow"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Cron: Every monday at 10:00 AM
  # schedule:
  #   - cron: "0 10 * * 1"
  # Save our planet

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: "0"

      - name: Install Depot Tools
        uses: newkdev/setup-depot-tools@v1.0.1

      - name: Pre-fetch
        working-directory: /tmp
        run: |
          mkdir devtools

      # fetch devtools-frontend
      - name: Fetch devtools-frontend
        # Set work path at /tmp
        working-directory: /tmp/devtools/
        run: |
          fetch devtools-frontend

      # Build devtools-frontend
      - name: Build devtools-frontend
        # Set work path at /tmp
        working-directory: /tmp/devtools/devtools-frontend
        run: |
          gn gen out/Default
          autoninja -C out/Default
          # The output dir is /tmp/devtools/devtools-frontend/out/Default/gen/front_end

      # Rm files in Repo, keep hidden files
      - name: Rm files in Repo
        run: rm -rf *

      # Copy built files to Repo
      - name: Copy built files to Repo
        run: cp -r /tmp/devtools/devtools-frontend/out/Default/gen/front_end/* .

      # Commit
      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update"

      # Push
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: main
